---
linters-settings:
  misspell:
    locale: US
  gci:
    sections:
      - standard
      - default
      - prefix(github.com/hetznercloud)

linters:
  disable-all: true
  enable:
    - bodyclose
    - copyloopvar
    - errcheck
    - gci
    - gocritic
    - gofmt
    - goimports
    - gosimple
    - govet
    - ineffassign
    - misspell
    - prealloc
    - revive
    - rowserrcheck
    - staticcheck
    - typecheck
    - unparam
    - unused
    - whitespace

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
    - path: _test\.go
      text: unused-parameter
