version: 2

before:
  hooks:
    - ./hack/release-generate-deployment-yamls.sh {{ .Version }}

builds:
  - id: hcloud-csi-driver
    main: ./cmd
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - arm64
      - arm
    binary: hcloud-csi-driver

dockers:
  - build_flag_templates: [--platform=linux/amd64]
    dockerfile: Dockerfile
    goarch: amd64
    image_templates:
      - "hetznercloud/hcloud-csi-driver:{{ if not .IsSnapshot }}v{{ end }}{{ .Version }}-amd64"
    use: buildx

  - build_flag_templates: [--platform=linux/arm64]
    dockerfile: Dockerfile
    goarch: arm64
    image_templates:
      - "hetznercloud/hcloud-csi-driver:{{ if not .IsSnapshot }}v{{ end }}{{ .Version }}-arm64v8"
    use: buildx

  - build_flag_templates: [--platform=linux/arm/v6]
    dockerfile: Dockerfile
    goarch: arm
    goarm: 6
    image_templates:
      - "hetznercloud/hcloud-csi-driver:{{ if not .IsSnapshot }}v{{ end }}{{ .Version }}-armv6"
    use: buildx

docker_manifests:
  - name_template: hetznercloud/hcloud-csi-driver:{{ if not .IsSnapshot }}v{{ end }}{{ .Version }}
    image_templates:
      - hetznercloud/hcloud-csi-driver:{{ if not .IsSnapshot }}v{{ end }}{{ .Version }}-amd64
      - hetznercloud/hcloud-csi-driver:{{ if not .IsSnapshot }}v{{ end }}{{ .Version }}-arm64v8
      - hetznercloud/hcloud-csi-driver:{{ if not .IsSnapshot }}v{{ end }}{{ .Version }}-armv6

archives:
  - id: hcloud-csi-driver-archive
    builds:
      - hcloud-csi-driver
    name_template: "{{ .Binary }}-{{ .Os }}-{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
    files:
      - LICENSE
      - README.md

release:
  ids:
    - hcloud-csi-driver-archive
  extra_files:
    - glob: "./hcloud-csi-{{ .Version }}.tgz"

publishers:
  - name: publish-helm-chart

    # Filter all artifacts, except the one generated by "release.extra_files" that
    # cannot be filtered. If the "release" step does not run, the publisher will have
    # not artifacts to publish.
    ids: ["none"]

    cmd: ./hack/release-publish-helm-chart.sh hcloud-csi-{{ .Version }}.tgz
    env:
      - CHART_REPO_REMOTE={{ .Env.CHART_REPO_REMOTE }}
      # Ensures we only publish once, when $1 == $GORELEASER_ARTIFACT_FILE
      - GORELEASER_ARTIFACT_FILE={{ .ArtifactPath }}
