version: 2

before:
  hooks:
    - ./hack/release-generate-deployment-yamls.sh {{ .Version }}

builds:
  - id: controller
    main: ./cmd/controller
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - arm64
      - arm
    binary: controller.bin
  - id: node
    main: ./cmd/node
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - arm64
      - arm
    binary: node.bin

dockers:
  - build_flag_templates: [--platform=linux/amd64]
    dockerfile: Dockerfile
    goarch: amd64
    image_templates: ["hetznercloud/hcloud-csi-driver:{{ if not .IsSnapshot }}v{{ end }}{{ .Version }}-amd64"]
    use: buildx

  - build_flag_templates: [--platform=linux/arm64]
    dockerfile: Dockerfile
    goarch: arm64
    image_templates: ["hetznercloud/hcloud-csi-driver:{{ if not .IsSnapshot }}v{{ end }}{{ .Version }}-arm64v8"]
    use: buildx

  - build_flag_templates: [--platform=linux/arm/v6]
    dockerfile: Dockerfile
    goarch: arm
    goarm: 6
    image_templates: ["hetznercloud/hcloud-csi-driver:{{ if not .IsSnapshot }}v{{ end }}{{ .Version }}-armv6"]
    use: buildx

docker_manifests:
  - name_template: hetznercloud/hcloud-csi-driver:{{ if not .IsSnapshot }}v{{ end }}{{ .Version }}
    image_templates:
      - hetznercloud/hcloud-csi-driver:{{ if not .IsSnapshot }}v{{ end }}{{ .Version }}-amd64
      - hetznercloud/hcloud-csi-driver:{{ if not .IsSnapshot }}v{{ end }}{{ .Version }}-arm64v8
      - hetznercloud/hcloud-csi-driver:{{ if not .IsSnapshot }}v{{ end }}{{ .Version }}-armv6

release:
  ids: [""]
  extra_files:
    - glob: "./hcloud-csi-*.tgz"

publishers:
  - name: helm-chart-repo

    # make sure that this is only executed once. There are no separate ids per binary built,
    # we filter for no actual ID and then run the publisher for the checksum.
    ids: [""]
    checksum: true

    cmd: ./hack/release-publish-helm-chart.sh hcloud-csi-{{ .Version }}.tgz
    env:
      - CHART_REPO_REMOTE={{ .Env.CHART_REPO_REMOTE }}
