apiVersion: skaffold/v4beta11
kind: Config
metadata:
  name: csi-driver
build:
  artifacts:
    - image: docker.io/hetznercloud/hcloud-csi-driver
      docker:
        dockerfile: dev/Dockerfile
        buildArgs:
          GO_BUILDFLAGS: -covermode=atomic -coverpkg=github.com/hetznercloud/csi-driver/...
  local:
    useBuildkit: true
  insecureRegistries:
    - localhost:30666

deploy:
  helm:
    releases:
      - name: hcloud-csi
        namespace: kube-system
        chartPath: chart
        setValues:
          controller.extraEnvVars[0].name: GOCOVERDIR
          controller.extraEnvVars[0].value: "/coverage"
          controller.extraVolumes[0].name: coverage
          controller.extraVolumes[0].emptyDir: {}
          controller.extraVolumeMounts[0].name: coverage
          controller.extraVolumeMounts[0].mountPath: "/coverage"

          node.extraEnvVars[0].name: GOCOVERDIR
          node.extraEnvVars[0].value: "/coverage"
          node.extraVolumes[0].name: coverage
          node.extraVolumes[0].emptyDir: {}
          node.extraVolumeMounts[0].name: coverage
          node.extraVolumeMounts[0].mountPath: "/coverage"
