apiVersion: skaffold/v4beta11
kind: Config
metadata:
  name: csi-driver
build:
  artifacts:
    - image: docker.io/hetznercloud/hcloud-csi-driver
      docker:
        dockerfile: dev/Dockerfile
  local:
    useBuildkit: true
  insecureRegistries:
    - localhost:30666

manifests:
  helm:
    releases:
      - name: hcloud-csi
        namespace: kube-system
        chartPath: chart
