apiVersion: skaffold/v4beta3
kind: Config
metadata:
  name: csi-driver
build:
  artifacts:
    - image: hetznercloud/hcloud-csi-driver
      docker:
        dockerfile: hack/Dockerfile
        cacheFrom:
          - hetznercloud/hcloud-csi-driver:buildcache
  local:
    useBuildkit: true
  insecureRegistries:
    - localhost:30666
manifests:
  kustomize:
    paths: [hack/]
