# This Kustomization is specifically designed for the Skaffold-powered dev environment.
# $ eval $(hack/dev-up.sh) && skaffold dev

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../deploy
patches:
  - patch: |-
      kind: DaemonSet
      apiVersion: apps/v1
      metadata:
        name: hcloud-csi-node
        namespace: kube-system
      spec:
        template:
          spec:
            containers:
            - name: hcloud-csi-driver
              env:
              - name: LOG_LEVEL
                value: info
              # - name: HCLOUD_DEBUG
              #   value: "true"

  - patch: |-
      kind: Deployment
      apiVersion: apps/v1
      metadata:
        name: hcloud-csi-controller
        namespace: kube-system
      spec:
        template:
          spec:
            containers:
            - name: hcloud-csi-driver
              env:
              - name: LOG_LEVEL
                value: info
              # - name: HCLOUD_DEBUG
              #   value: "true"
