{{- if .Values.controller.hcloudToken.value }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "hcloud-csi.names.fullname" . }}-hcloud-token
  namespace: {{ include "hcloud-csi.names.namespace" . | quote }}
  labels: {{- include "hcloud-csi.labels.standard" . | nindent 4 }}
    app.kubernetes.io/component: controller
    {{- if .Values.commonLabels }}
    {{- include "hcloud-csi.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "hcloud-csi.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
type: Opaque
data:
  token: {{ .Values.controller.hcloudToken.value | b64enc }}
{{- end }}
